config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  #user routes
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update', as: 'update_user'
  delete '/users/:id', to: 'users#destroy', as: 'delete_user'

  #sessions routes
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  post '/sessions', to: 'sessions#create', as: 'new_session'

  #movie routes
  get '/movies', to: 'movies#index', as: 'movies'
  post '/movies', to: 'movies#create', as: 'create_movie'
  get '/movies/:movie_id', to: 'movies#show', as: 'movie'

  #movie review routes
  get '/reviews', to: 'reviews#index', as: 'reviews'
  get '/movies/:id', to:'reviews#index', as: 'movie_reviews'
  post '/movies/:id', to: 'reviews#create', as: 'create_review'
  get '/movies/:id/reviews/new', to:'reviews#new', as: 'new_review'
  get 'reviews/:id/edit', to: 'reviews#edit', as: 'edit_review'
  patch '/movies/:movie_id/reviews/:review_id', to: 'reviews#update', as: 'update_review'
  delete '/movies/:movie_id/reviews/:review_id', to: 'reviews#destroy', as: 'delete_review'

end

app/controllers/movies_controller.rb
require 'httparty'
class MoviesController < ApplicationController
  include HTTParty

  def index
      if params[:search]
        # search params only pull up these attributes: title, year, imdbid, type & poster
        search_response = HTTParty.get('https://www.omdbapi.com/?apikey=' + Rails.application.credentials[:ombd_api_key] + '&s=' + params[:search] + '&r=json')
        # if response is success, insert movies pulled up in search into empty array
        if search_response.success?
          search = search_response["Search"]
          @movies = [] #empty array to insert search results
          search.each do |search_result_item|
              mov = Movie.find_or_create_by(imdbid: search_result_item['imdbID']) do |new_movie| # create list of movies found based off of search parameters
                new_movie.title = search_result_item["Title"]
                new_movie.poster = search_result_item["Poster"]
                new_movie.year = search_result_item["Year"]
              end # end "new_movie" iteration
              @movies << mov # push search result into array
          end #end "search_result_item" iteration

        else # if search_response fails, throw error
          p 'error'

        end # end search_response if-case
      else # if no search params, display all movies in database.
        @movies = Movie.all
      end # end search params if-case
  end # end 'def index'

  def show
    @movie = Movie.find(params[:movie_id])
    movie_response = HTTParty.get('https://www.omdbapi.com/?apikey=' + Rails.application.credentials[:ombd_api_key] + '&t=' + @movie.title + '&y=&plot=full&r=json')
    movie_response_short_plot = HTTParty.get('https://www.omdbapi.com/?apikey=' + Rails.application.credentials[:ombd_api_key] + '&t=' + @movie.title + '&y=&r=json')
    @plotShort = movie_response_short_plot["Plot"]
    @plotFull = movie_response
    @genre = movie_response["Genre"]
    @maturityRating = movie_response["Rated"]
    # @rottenRating = movie_response["Plot"]
    # @imdbRating = movie_response["Plot"]
    @reviews = @movie.reviews
    @reviews.each do |review|
    @user = User.find_by_id(review.user_id)
  end

    if @rating == true # if there is a rating, display the rating, otherwise, set rating score to 0
      if @user == true  # if the user is logged in, tie in user id to allow contribution to rating score, if not, simply show the rating
        @rating = Rating.where(movie_id: @movie.id, user_id: current_user.id).first
      else
        @rating = Rating.where(movie_id: @movie.id).first
      end #end secondary if case for existence of user
    else
      if @user == true
        @rating = Rating.create(movie_id: @movie.id, user_id: current_user.id, score: 0)
      else
        @rating = Rating.create(movie_id: @movie.id, score: 0)
      end #end secondary if case for existence of user
    end
    render :show
  end #end to main if case for review score

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>

<div class= "container-fluid">
  <div class= "row">
    <div class= "col-md-12">
      <div class = "bg">
        <div class= "container">
          <div class="jumbotron jumbotron-fluid">
            <h2 class="align-middle">Movies</h2>
            <h2 class="align-middle">Index</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class= "container">
  <div class = "row">
    <form class="form-inline search-bar">
      <%= form_tag movies_path, {method: 'get'} do %>
        <%= text_field_tag :search, params[:search], class:'form-control', placeholder:"Search movies"%>
        <%= submit_tag "Search", name: nil, class: "btn btn-secondary-outline" %>
      <% end %>
    </form>
  </div>
</div>


  <div class="panel panel-default">
    <div class="panel-body">
        <div class= "row justify-content-center">
          <div class= "col-12">
            <% @movies.each do |movie|%>

              <div class="col-lg-2 col-md-3 col-sm-6 col-xs-12 mb-3">
                  <div class="card center-block">
                    <div class = "card-body">
                        <% if movie.poster === "N/A" %>
                          <p><a href="#" data-toggle="modal" data-target="#modal-<%= movie.id %>"><%= image_tag('http://www.interlog.com/~tfs/images/posters/TFSMoviePosterUnavailable.jpg', class: 'card-img-top center-block mb-1') %></a></p>
                        <% else %>
                          <p><a href="#" data-toggle="modal" data-target="#modal-<%= movie.id %>"><%= image_tag(movie.poster, class: 'card-img-top center-block mb-1') %></a></p>
                        <% end %>
                        <p class="card-text center-block"> <a href="#" class = "movie-title-text" data-toggle="modal" data-target="#modal-<%= movie.id %>"><%= movie.title %></a></p>
                        </div>
                  </div>
              </div>

              <!-- Modal Window -->
              <div class="modal fade" id="modal-<%= movie.id %>" role="dialog" aria-labelledby="movieModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="movieModalLabel"><%= movie.title %></h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <div class = "col-md-6"><%= image_tag(movie.poster)%></div>

                      <div class = "col-md-6"><%= movie.plot %></div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Add to Watchlist</button>
                      <%= link_to "More..", movie_path(movie), :class => "btn btn-default" %>
                    </div>
                  </div>
                </div>
              </div>
              <!-- End Modal -->

            <% end %>
            <br>
            <br>
        </div>
      </div>
    </div>
  </div>

app/views/movies/show.html.erb
<html>
<body>
    <div class="container">
        <h1><%= @movie.title %></h1>
        <p>
          <% if @movie.poster === "N/A" %>
            <img src = "http://www.interlog.com/~tfs/images/posters/TFSMoviePosterUnavailable.jpg" class= "img-responsive">
          <% else %>
            <%= image_tag @movie.poster, class:'img-responsive poster' %>
          <% end %>
        </p>
        <p><b>Released:</b><%= @movie.year%></p>
        <p><b>Genre:</b><%= @genre %></p>
        <p><%= @plot %></p><br>
        <br>
        <!--avg rating -->
        <p>Average rating</p>
        <div id="star">
          <script>
          $('#star').raty({
            readOnly: true,
            score: <%= @movie.average_rating %>,
            path: '/assets'
          });
          </script>
        </div>
        <hr>
        <!--end avg rating  -->
        <% if current_user%>
          <%= link_to "Add Review", new_review_path(@movie), class:"btn btn-success"%>
        <%end%>
        <hr>
        <div class="col-md-12">
            <h2>Reviews:</h2><br>
            <%@reviews.each do |review| %>
            <div id="show_star">
              <script>
                $('#user_star').raty({
                  score: <%= @rating.score %>,
                });
              </script>
            </div>
            <div class="media">
                <div class="media-left">
                    <%= image_tag @user.image, class: 'media-object', height: 50 %>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">
                    <%= link_to @user.username, user_path(@user) %>:
                    "<%= review.subject %>"</h4><span><%= link_to '', delete_review_path(@movie, review), method: 'delete', class: "glyphicon glyphicon-remove"%></span>
                    <span><%= link_to '', edit_review_path(review), class: "glyphicon glyphicon-pencil" %></span>
                    <b>Rating:</b> <%=review.rating%><br>
                    <p><em><%= review.content %></em></p>
                </div>
            </div><%end%>
        </div>
    </div>
</body>
</html>