config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  #user routes
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update', as: 'update_user'
  delete '/users/:id', to: 'users#destroy', as: 'delete_user'

  #sessions routes
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  post '/sessions', to: 'sessions#create', as: 'new_session'

  #movie routes
  get '/movies', to: 'movies#index', as: 'movies'
  post '/movies', to: 'movies#create', as: 'create_movie'
  get '/movies/:movie_id', to: 'movies#show', as: 'movie'

  #movie review routes
  get '/reviews', to: 'reviews#index', as: 'reviews'
  get '/movies/:id', to:'reviews#index', as: 'movie_reviews'
  post '/movies/:id', to: 'reviews#create', as: 'create_review'
  get '/movies/:id/reviews/new', to:'reviews#new', as: 'new_review'
  get 'reviews/:id/edit', to: 'reviews#edit', as: 'edit_review'
  patch '/movies/:movie_id/reviews/:review_id', to: 'reviews#update', as: 'update_review'
  delete '/movies/:movie_id/reviews/:review_id', to: 'reviews#destroy', as: 'delete_review'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews
  has_many :movies, through: :reviews
  has_many :ratings
  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.create(user_params)
    @user.save
    login(@user)
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class ="col-md-6 ">
  <h1> Edit Profile </h1>
  <hr>
    <%= form_for @user do |f| %>

    <div>
      <%= f.text_field :username, placeholder: "Username", class: "form-control"%><br>
    </div>

    <div>
      <%= f.text_field :email, placeholder: "Email", class: "form-control" %><br>
    </div>

    <div>
      <%= f.password_field :password, placeholder: "Password", class: "form-control" %><br>
    </div>

    <div>
      <%= f.text_field :image, placeholder: "Image URL", class: "form-control" %><br>
    </div>

    <div>
      <%= f.submit :submit, class: "btn btn-success" %>
    </div>

  <% end %>
</div>

<%= button_to 'Delete Account', delete_user_path(@user), method: 'delete', class: 'btn btn-danger', data: {confirm: "are you sure? This action cannot be undone."} %>

app/views/users/index.html.erb
<div class="container splash">
      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <div class="jumbotron">
            <h1>Awfulix </h1>
            <p>Where horrible movies are all the rage? <img src="http://www.loyolafilmes.com.br/wp-content/uploads/2015/02/001-VHS.png" class= "img-responsive" height=10></p>
          </div>
          <div class="row">
            <div class="col-xs-6 col-lg-4">
              <h2>Not a member?</h2>
              <p>Sign up to be a part of our horrible movie loving community! Whatever 90's pour-over taxidermy, brooklyn bitters biodiesel pickled shabby chic tumblr cronut. Hashtag brooklyn chicharrones before they sold out distillery mixtape neutra. </p>
              <p><%= button_to "Sign up", new_user_path, class:"btn btn-default", method: "get" %></p>
            </div><!--/.col-xs-6.col-lg-4-->
            <div class="col-xs-6 col-lg-4">
              <h2>Log in!</h2>
              <p> If you're already signed up, click the Log in button to sign in. Austin mustache kogi, sartorial tofu typewriter synth XOXO.</p>
              <p><%= button_to "Log in", login_path, class:"btn btn-default", method: "get" %></p>
            </div><!--/.col-xs-6.col-lg-4-->
            <div class="col-xs-6 col-lg-4">
              <h2>Search Movies</h2>
              <p>Search movies here. Cardigan blue bottle venmo, green juice meditation tacos church-key lomo taxidermy PBR&B fanny pack. Listicle fanny pack gochujang keffiyeh.  </p>
              <p><%= button_to "Movies", reviews_path, class:"btn btn-default", method: "get" %></p>
            </div><!--/.col-xs-6.col-lg-4-->

app/views/users/new.html.erb
<div class="col-md-offset-3 col-md-6 col col-md-offset-3">
  <div class="user-form">
    <h1> Sign Up </h1>
    <hr>
    <%= form_for @user do |f| %>

    <div>
      <%= f.text_field :username, placeholder: "Username", class: "form-control"%><br>
    </div>

    <div>
      <%= f.text_field :email, placeholder: "Email", class: "form-control" %><br>
    </div>

    <div>
      <%= f.password_field :password, placeholder: "Password", class: "form-control" %><br>
    </div>

    <div>
      <%= f.text_field :image, placeholder: "Image URL", class: "form-control" %><br>
    </div>

    <div>
      <%= f.submit :submit, class: "btn btn-primary" %>
    </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-warning">
      <div class = "panel panel-heading"> <h2> <%= @user.username %> </h2></div>
        <p><%= image_tag @user.image, class: "img-responsive center-block"%></p>
        <p><b>Email: </b><%= @user.email %></p>
        <%= button_to 'Edit Account', edit_user_path(@user), method: 'get', class: 'btn btn-warning' %>
      </div>
    </div>
  </div>
</div>