config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  #user routes
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update', as: 'update_user'
  delete '/users/:id', to: 'users#destroy', as: 'delete_user'

  #sessions routes
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  post '/sessions', to: 'sessions#create', as: 'new_session'

  #movie routes
  get '/movies', to: 'movies#index', as: 'movies'
  post '/movies', to: 'movies#create', as: 'create_movie'
  get '/movies/:movie_id', to: 'movies#show', as: 'movie'

  #movie review routes
  get '/reviews', to: 'reviews#index', as: 'reviews'
  get '/movies/:id', to:'reviews#index', as: 'movie_reviews'
  post '/movies/:id', to: 'reviews#create', as: 'create_review'
  get '/movies/:id/reviews/new', to:'reviews#new', as: 'new_review'
  get 'reviews/:id/edit', to: 'reviews#edit', as: 'edit_review'
  patch '/movies/:movie_id/reviews/:review_id', to: 'reviews#update', as: 'update_review'
  delete '/movies/:movie_id/reviews/:review_id', to: 'reviews#destroy', as: 'delete_review'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @review_all = Review.all

  end

  def new
    @movie = Movie.find(params[:id])
    @review = Review.new
    @rating = Rating.create(movie_id: @movie.id, user_id: current_user.id, score: 0)

    render :new
  end

  def create
    @review = Review.new(review_params)
    @rating = Rating.find(params[:id])
    @rating.update_attributes(score: params[:score])
    @user = current_user
    @movie = Movie.find(params[:id])
    @movie.reviews << @review
    @user.reviews << @review
    @movie.ratings << @rating
    @user.ratings << @rating
    @movie.save
    @user.save
    # @review.save

    redirect_to movie_reviews_path(@movie)
  end

  def edit
    @review = Review.find(params[:id])
    @movie = Movie.find_by_id(@review.movie_id)
    render :edit
  end

  def update
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:review_id])
    @review.update_attributes(review_params)


    redirect_to movie_reviews_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:review_id])
    @review.destroy

    redirect_to movie_path(@movie)
  end


  private
  def review_params
    params.require(:review).permit(:content, :rating, :subject)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<!-- views/reviews/edit.html.erb -->
<div class= 'container'>
  <div class ='col-md-6'>
    <h1><%=@movie.title%></h1>
    <%= image_tag @movie.poster%>
    <%= form_for @review, url: update_review_path(@movie, @review) do |f| %>
      <h4>Edit Review:</h4>
      <hr>

      <div>
        <%= f.label :subject %>
        <%= f.text_field :subject, class:'form-control' %>
      </div><br>

      <div>
        <%= f.label :rating %>
        <%= f.number_field :rating, class:'form-control' %>
      </div><br>

      <div>
        <%= f.label :content, "Review" %>
        <%= f.text_area :content, class:'form-control' %>
      </div><br>

      <div>
        <%= f.submit :submit, class:'btn btn-primary' %>
      </div>

    <% end %>
  </div>
</div>

app/views/reviews/index.html.erb
<!-- views/reviews/index.html.erb -->
<div class= "container">
<h1> All Reviews </h1>

<% @review_all.each do |review| %>

  <h5>"<%=review.subject %>"<br></h5>
  <i>"<%=review.content %>"</i>
<% end %>
</div>

app/views/reviews/new.html.erb
<!-- views/reviews/new.html.erb -->
<div class= 'container'>
  <div class ='col-md-6'>
    <h1><%=@movie.title%></h1>
    <%= image_tag @movie.poster%>
    <%= form_for @review , url: create_review_path do |f| %>
      <h4>New Review:</h4>
      <hr>

      <div>
        <%= f.label :subject, "Subject:" %>
        <%= f.text_field :subject, class:'form-control' %>
      </div><br>

      <!--user rating  -->
      <b>Rating:</b>
      <div id="user_star">
        <script>
          $('#user_star').raty({
            score: <%= @rating.score %>,
            path: '/assets',
            click: function(score, evt) {
              $.ajax({
                url: '/ratings/' + <%= @rating.id %>,
                type: 'PATCH',
                data: { score: score }
              }).done(function (data){});
            }
          });
        </script>
      </div>
      <!--end user rating  -->

      <div>
        <%= f.label :content, "Review:" %>
        <%= f.text_area :content, class:'form-control' %>
      </div><br>

      <div>
        <%= f.submit :submit, class:'btn btn-primary' %>
      </div>

    <% end %>
  </div>
</div>