config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  #user routes
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update', as: 'update_user'
  delete '/users/:id', to: 'users#destroy', as: 'delete_user'

  #sessions routes
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  post '/sessions', to: 'sessions#create', as: 'new_session'

  #movie routes
  get '/movies', to: 'movies#index', as: 'movies'
  post '/movies', to: 'movies#create', as: 'create_movie'
  get '/movies/:movie_id', to: 'movies#show', as: 'movie'

  #movie review routes
  get '/reviews', to: 'reviews#index', as: 'reviews'
  get '/movies/:id', to:'reviews#index', as: 'movie_reviews'
  post '/movies/:id', to: 'reviews#create', as: 'create_review'
  get '/movies/:id/reviews/new', to:'reviews#new', as: 'new_review'
  get 'reviews/:id/edit', to: 'reviews#edit', as: 'edit_review'
  patch '/movies/:movie_id/reviews/:review_id', to: 'reviews#update', as: 'update_review'
  delete '/movies/:movie_id/reviews/:review_id', to: 'reviews#destroy', as: 'delete_review'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Awfulix</title><%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %><%= javascript_include_tag 'application', 'data-turbolinks-track' => true %><%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans:400&subset=latin', media: 'all', 'data-turbolinks-track' => true %><%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=3">
</head>
<body style = "background-color: #f5f9ea;">
    <!-- Google font  -->
    <link href='https://fonts.googleapis.com/css?family=Press+Start+2P' rel=
    'stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Creepster" rel="stylesheet">
    <!-- new nav -->
    <nav class="navbar navbar-light navbar-fixed-top" style=
    "background-color: #92A06A;">
        <div class="container">
            <div class="row">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="/"><b>  Awfulix</b></a></li>
                    <li><%=link_to "Movies", movies_path %></li>
                    <%if current_user %>
                      <li><%=link_to "Profile", user_path(current_user) %></li>
                    <%end %>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <%if current_user %>
                      <li class><%=link_to "Logout", logout_path%></li>
                    <%else %>
                      <li><%=link_to "Login", login_path%></li>
                      <li><%=link_to "Sign Up", new_user_path%></li>
                    <%end%>
                </ul>
            </div>
        </div>
    </nav><!-- new nav -->
    <div class = "container">
      <% flash.each do |type, message| %>
        <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= message %>
        </div>
      <% end %>
    </div>

    <%= yield %>
</body>
</html>